### ISSUE TITLE
Error while running local plugin

### ISSUE THREAD

**Issue by ssutar** [dyfactor/dyfactor#8]
Trying to develop a local plugin `ember-object` added as dev dependency:
```
$ yarn dyfactor list-plugins
yarn run v1.10.1
$ /work/super-rentals/node_modules/.bin/dyfactor list-plugins

Plugins
=============
Name: ember-object Type: template Levels: extract, modify
✨  Done in 0.73s.
```
But when tried to run:
```
$ yarn dyfactor run template ember-object ./app/ --level extract
yarn run v1.10.1
$ /work/super-rentals/node_modules/.bin/dyfactor run template ember-object ./app/ --level extract
(node:75722) UnhandledPromiseRejectionWarning: Error: Cannot find module 'dyfactor-plugin-ember-object' from '/Users/work/super-rentals'
    at Function.module.exports [as sync] (/work/super-rentals/node_modules/dyfactor/node_modules/resolve/lib/sync.js:43:15)
    at Environment.lookupPlugin (/work/super-rentals/node_modules/dyfactor/dist/commonjs/src/runtime/environment.js:58:32)
    at Runner.<anonymous> (/work/super-rentals/node_modules/dyfactor/dist/commonjs/src/runtime/runner.js:19:30)
    at Generator.next (<anonymous>)
    at /work/super-rentals/node_modules/dyfactor/dist/commonjs/src/runtime/runner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/work/super-rentals/node_modules/dyfactor/dist/commonjs/src/runtime/runner.js:3:12)
    at Runner.run (/work/super-rentals/node_modules/dyfactor/dist/commonjs/src/runtime/runner.js:17:16)
    at Command.program.option.action (/work/super-rentals/node_modules/dyfactor/bin/dyfactor-run:46:20)
    at Command.listener (/work/super-rentals/node_modules/commander/index.js:315:8)
(node:75722) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:75722) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.54s.
```

This is how the dev dependencies are added in package.json
```
+    "dyfactor": "^0.4.1",
+    "dyfactor-plugin-ember-object": "file:../dyfactor-plugin-ember-object/",
```

**Comment by ssutar** [comment]
Figured out what the issue was, issue is with my local setup, `package.json` main entry was pointing to incorrect path. My bad 😞 

Closing the issue!
